/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *cadena;

#define CALCULADORA_PROG 0x20000001
#define CALCULADORA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define cant_carac_e 1
extern  int * cant_carac_e_1(cadena *, CLIENT *);
extern  int * cant_carac_e_1_svc(cadena *, struct svc_req *);
#define cant_carac_se 2
extern  int * cant_carac_se_1(cadena *, CLIENT *);
extern  int * cant_carac_se_1_svc(cadena *, struct svc_req *);
#define cant_palabras 3
extern  int * cant_palabras_1(cadena *, CLIENT *);
extern  int * cant_palabras_1_svc(cadena *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cant_carac_e 1
extern  int * cant_carac_e_1();
extern  int * cant_carac_e_1_svc();
#define cant_carac_se 2
extern  int * cant_carac_se_1();
extern  int * cant_carac_se_1_svc();
#define cant_palabras 3
extern  int * cant_palabras_1();
extern  int * cant_palabras_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cadena (XDR *, cadena*);

#else /* K&R C */
extern bool_t xdr_cadena ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
