/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROCESO_H_RPCGEN
#define _PROCESO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_MSG 256
#define MAX_NOMBRE 128

enum estado {
	OK = 0,
	NO_EXISTE = 1,
	SIN_PERMISO = 2,
	NO_FINALIZO = 3,
	PROHIBIDO = 4,
	ERROR = 5,
};
typedef enum estado estado;

struct respuesta {
	estado codigo;
	int cantidad;
	char *mensaje;
};
typedef struct respuesta respuesta;

typedef char *nombre_proc;

#define TERMINAR_PROG 0x31234567
#define TERMINAR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TERMINAR_POR_PID 1
extern  respuesta * terminar_por_pid_1(int *, CLIENT *);
extern  respuesta * terminar_por_pid_1_svc(int *, struct svc_req *);
#define TERMINAR_POR_NOMBRE 2
extern  respuesta * terminar_por_nombre_1(nombre_proc *, CLIENT *);
extern  respuesta * terminar_por_nombre_1_svc(nombre_proc *, struct svc_req *);
extern int terminar_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TERMINAR_POR_PID 1
extern  respuesta * terminar_por_pid_1();
extern  respuesta * terminar_por_pid_1_svc();
#define TERMINAR_POR_NOMBRE 2
extern  respuesta * terminar_por_nombre_1();
extern  respuesta * terminar_por_nombre_1_svc();
extern int terminar_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_estado (XDR *, estado*);
extern  bool_t xdr_respuesta (XDR *, respuesta*);
extern  bool_t xdr_nombre_proc (XDR *, nombre_proc*);

#else /* K&R C */
extern bool_t xdr_estado ();
extern bool_t xdr_respuesta ();
extern bool_t xdr_nombre_proc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROCESO_H_RPCGEN */
