/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proceso.h"

bool_t
xdr_estado (XDR *xdrs, estado *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_respuesta (XDR *xdrs, respuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_estado (xdrs, &objp->codigo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->mensaje, MAX_MSG))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nombre_proc (XDR *xdrs, nombre_proc *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_NOMBRE))
		 return FALSE;
	return TRUE;
}
