/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "proceso.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

respuesta *
terminar_por_pid_1(int *argp, CLIENT *clnt)
{
	static respuesta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TERMINAR_POR_PID,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_respuesta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

respuesta *
terminar_por_nombre_1(nombre_proc *argp, CLIENT *clnt)
{
	static respuesta clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TERMINAR_POR_NOMBRE,
		(xdrproc_t) xdr_nombre_proc, (caddr_t) argp,
		(xdrproc_t) xdr_respuesta, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
