/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "media.h"
#include <stdio.h>
#include <stdlib.h>

void mediaprog_1(char *host)
{
	CLIENT *clnt;
	respuesta_media *result_1;
	arreglo_enteros args;
	int n, i;

#ifndef DEBUG
	clnt = clnt_create(host, MEDIAPROG, MEDIAVERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	printf("Ingrese la cantidad de elementos del arreglo (0 para probar arreglo vacio): ");
	scanf("%d", &n);

	if (n < 0 || n > 100)
	{
		printf("Tamano no valido.\n");
		return;
	}

	args.numeros.numeros_len = n;

	/* Reservar memoria solo si hay elementos */
	if (n > 0)
	{
		args.numeros.numeros_val = (int *)malloc(n * sizeof(int));
		for (i = 0; i < n; i++)
		{
			printf("Elemento %d: ", i + 1);
			scanf("%d", &args.numeros.numeros_val[i]);
		}
	}
	else
	{
		args.numeros.numeros_val = NULL; /* Arreglo vacío */
	}

	result_1 = calcular_media_1(&args, clnt);

	if (result_1 == (respuesta_media *)NULL)
	{
		clnt_perror(clnt, "Fallo en la llamada RPC");
	}
	else
	{
		if (result_1->status == 1)
		{
			printf("El arreglo no contiene elementos\n");
		}
		else
		{
			printf("La media aritmetica es: %.2f\n", result_1->media);
		}
	}

	if (n > 0)
	{
		free(args.numeros.numeros_val);
	}
	if (result_1 == (respuesta_media *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	mediaprog_1(host);
	exit(0);
}
