/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MEDIA_H_RPCGEN
#define _MEDIA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SIZE 100

struct arreglo_enteros {
	struct {
		u_int numeros_len;
		int *numeros_val;
	} numeros;
};
typedef struct arreglo_enteros arreglo_enteros;

struct respuesta_media {
	float media;
	int status;
};
typedef struct respuesta_media respuesta_media;

#define MEDIAPROG 0x20000002
#define MEDIAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULAR_MEDIA 1
extern  respuesta_media * calcular_media_1(arreglo_enteros *, CLIENT *);
extern  respuesta_media * calcular_media_1_svc(arreglo_enteros *, struct svc_req *);
extern int mediaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULAR_MEDIA 1
extern  respuesta_media * calcular_media_1();
extern  respuesta_media * calcular_media_1_svc();
extern int mediaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arreglo_enteros (XDR *, arreglo_enteros*);
extern  bool_t xdr_respuesta_media (XDR *, respuesta_media*);

#else /* K&R C */
extern bool_t xdr_arreglo_enteros ();
extern bool_t xdr_respuesta_media ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MEDIA_H_RPCGEN */
