/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "media.h"
#include <stdio.h>

respuesta_media *calcular_media_1_svc(arreglo_enteros *argp, struct svc_req *rqstp)
{
	static respuesta_media result;

	int i;
	float suma = 0;

	printf("Servidor: Solicitud recibida con %d elementos.\n", argp->numeros.numeros_len);

	if (argp->numeros.numeros_len == 0)
	{
		result.status = 1;
		result.media = 0.0;
	}
	else
	{
		for (i = 0; i < argp->numeros.numeros_len; i++)
		{
			suma += argp->numeros.numeros_val[i];
		}
		result.media = suma / argp->numeros.numeros_len;
		result.status = 0;
	}

	/*
	 * insert server code here
	 */

	return &result;
}
