/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "media.h"

bool_t
xdr_arreglo_enteros (XDR *xdrs, arreglo_enteros *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->numeros.numeros_val, (u_int *) &objp->numeros.numeros_len, MAX_SIZE,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_respuesta_media (XDR *xdrs, respuesta_media *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->media))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
